import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import MainNav from "@/components/mainNav";
import Providers from "./providers";
import styles from "./page.module.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "title",
  description: "Generated by Marijana",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <MainNav />
        <Providers>{children}</Providers>
        <footer className={styles.footer}>
          <p>
            © {new Date().getFullYear()} Recipe App by Marijana Maslać,
            Sveučilišni odjel za stručne studije, Split
          </p>
        </footer>
      </body>
    </html>
  );
}
